//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto_skolaAPI.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odgovor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odgovor()
        {
            this.OznaceniOdgovori = new HashSet<OznaceniOdgovori>();
        }
    
        public int OdgovorId { get; set; }
        public string Odgovor1 { get; set; }
        public Nullable<bool> IsTacan { get; set; }
        public int PitanjeId { get; set; }
    
        public virtual Pitanje Pitanje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OznaceniOdgovori> OznaceniOdgovori { get; set; }
    }
}
