//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto_skolaAPI.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pitanje()
        {
            this.Odgovor = new HashSet<Odgovor>();
            this.OznaceniOdgovori = new HashSet<OznaceniOdgovori>();
        }
    
        public int PitanjeId { get; set; }
        public string Pitanje1 { get; set; }
        public byte[] Slika { get; set; }
        public int TipPitanjaId { get; set; }
        public int TestId { get; set; }
        public byte[] SlikaThumb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odgovor> Odgovor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OznaceniOdgovori> OznaceniOdgovori { get; set; }
        public virtual Test Test { get; set; }
        public virtual TipPitanja TipPitanja { get; set; }
    }
}
