//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto_skolaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izbor
    {
        public int IzborId { get; set; }
        public string Naziv { get; set; }
        public byte[] Slika { get; set; }
        public Nullable<System.DateTime> DatumUpisivanja { get; set; }
        public Nullable<System.DateTime> DatumIzmjene { get; set; }
        public Nullable<int> KorisnikId { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
    }
}
