//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto_skolaAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class auto_skolaEntities : DbContext
    {
        public auto_skolaEntities()
            : base("name=auto_skolaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Izbor> Izbor { get; set; }
        public virtual DbSet<Kandidati> Kandidati { get; set; }
        public virtual DbSet<Kategorija> Kategorija { get; set; }
        public virtual DbSet<Korisnici> Korisnici { get; set; }
        public virtual DbSet<KorisniciUloge> KorisniciUloge { get; set; }
        public virtual DbSet<NacinPlacanja> NacinPlacanja { get; set; }
        public virtual DbSet<Ocjene> Ocjene { get; set; }
        public virtual DbSet<Odgovor> Odgovor { get; set; }
        public virtual DbSet<OznaceniOdgovori> OznaceniOdgovori { get; set; }
        public virtual DbSet<Pitanje> Pitanje { get; set; }
        public virtual DbSet<Podkategorija> Podkategorija { get; set; }
        public virtual DbSet<Polaze> Polaze { get; set; }
        public virtual DbSet<Rezultat> Rezultat { get; set; }
        public virtual DbSet<Spol> Spol { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Termin> Termin { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TipPitanja> TipPitanja { get; set; }
        public virtual DbSet<Uloge> Uloge { get; set; }
        public virtual DbSet<Upisuje> Upisuje { get; set; }
        public virtual DbSet<Uplata> Uplata { get; set; }
        public virtual DbSet<Vozilo> Vozilo { get; set; }
        public virtual DbSet<StrucnaSprema> StrucnaSprema { get; set; }
        public virtual DbSet<TipIspita> TipIspita { get; set; }
        public virtual DbSet<VozackiIspit> VozackiIspit { get; set; }
    
        public virtual ObjectResult<asp_Instruktori_SelectAll_Result> asp_Instruktori_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Instruktori_SelectAll_Result>("asp_Instruktori_SelectAll");
        }
    
        public virtual ObjectResult<asp_Izbor_GetIzborById_Result> asp_Izbor_GetIzborById(Nullable<int> izborId)
        {
            var izborIdParameter = izborId.HasValue ?
                new ObjectParameter("IzborId", izborId) :
                new ObjectParameter("IzborId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Izbor_GetIzborById_Result>("asp_Izbor_GetIzborById", izborIdParameter);
        }
    
        public virtual ObjectResult<asp_Izbor_SelectAll_Result> asp_Izbor_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Izbor_SelectAll_Result>("asp_Izbor_SelectAll");
        }
    
        public virtual ObjectResult<Nullable<int>> asp_Kandidati_GetBrojNovihKandidata(Nullable<int> korisnikId)
        {
            var korisnikIdParameter = korisnikId.HasValue ?
                new ObjectParameter("KorisnikId", korisnikId) :
                new ObjectParameter("KorisnikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("asp_Kandidati_GetBrojNovihKandidata", korisnikIdParameter);
        }
    
        public virtual ObjectResult<asp_Kandidati_GetById_Result> asp_Kandidati_GetById(Nullable<int> korisnikId)
        {
            var korisnikIdParameter = korisnikId.HasValue ?
                new ObjectParameter("KorisnikId", korisnikId) :
                new ObjectParameter("KorisnikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Kandidati_GetById_Result>("asp_Kandidati_GetById", korisnikIdParameter);
        }
    
        public virtual ObjectResult<asp_Kandidati_GetByUsername_Result> asp_Kandidati_GetByUsername(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Kandidati_GetByUsername_Result>("asp_Kandidati_GetByUsername", usernameParameter);
        }
    
        public virtual ObjectResult<asp_Kandidati_SearchByName_Result> asp_Kandidati_SearchByName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Kandidati_SearchByName_Result>("asp_Kandidati_SearchByName", nameParameter);
        }
    
        public virtual ObjectResult<asp_Kandidati_SelectAll_Result> asp_Kandidati_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Kandidati_SelectAll_Result>("asp_Kandidati_SelectAll");
        }
    
        public virtual ObjectResult<asp_Kandidati_SpojenoImePrezime_Result> asp_Kandidati_SpojenoImePrezime()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Kandidati_SpojenoImePrezime_Result>("asp_Kandidati_SpojenoImePrezime");
        }
    
        public virtual ObjectResult<asp_Kategorija_GetById_Result> asp_Kategorija_GetById(Nullable<int> kategorijaId)
        {
            var kategorijaIdParameter = kategorijaId.HasValue ?
                new ObjectParameter("KategorijaId", kategorijaId) :
                new ObjectParameter("KategorijaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Kategorija_GetById_Result>("asp_Kategorija_GetById", kategorijaIdParameter);
        }
    
        public virtual ObjectResult<asp_Kategorija_SelectAll_Result> asp_Kategorija_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Kategorija_SelectAll_Result>("asp_Kategorija_SelectAll");
        }
    
        public virtual ObjectResult<asp_Korisnici_GetById_Result> asp_Korisnici_GetById(Nullable<int> korisnikId)
        {
            var korisnikIdParameter = korisnikId.HasValue ?
                new ObjectParameter("KorisnikId", korisnikId) :
                new ObjectParameter("KorisnikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Korisnici_GetById_Result>("asp_Korisnici_GetById", korisnikIdParameter);
        }
    
        public virtual ObjectResult<asp_Korisnici_GetByUsername_Result> asp_Korisnici_GetByUsername(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Korisnici_GetByUsername_Result>("asp_Korisnici_GetByUsername", usernameParameter);
        }
    
        public virtual ObjectResult<asp_Korisnici_GetRecommendedInstruktori_Result> asp_Korisnici_GetRecommendedInstruktori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Korisnici_GetRecommendedInstruktori_Result>("asp_Korisnici_GetRecommendedInstruktori");
        }
    
        public virtual ObjectResult<asp_Korisnici_GetSlicnePoKandidatu_Result> asp_Korisnici_GetSlicnePoKandidatu(Nullable<int> spolId, Nullable<int> korisnikId, Nullable<System.DateTime> datumRodjenja)
        {
            var spolIdParameter = spolId.HasValue ?
                new ObjectParameter("SpolId", spolId) :
                new ObjectParameter("SpolId", typeof(int));
    
            var korisnikIdParameter = korisnikId.HasValue ?
                new ObjectParameter("KorisnikId", korisnikId) :
                new ObjectParameter("KorisnikId", typeof(int));
    
            var datumRodjenjaParameter = datumRodjenja.HasValue ?
                new ObjectParameter("DatumRodjenja", datumRodjenja) :
                new ObjectParameter("DatumRodjenja", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Korisnici_GetSlicnePoKandidatu_Result>("asp_Korisnici_GetSlicnePoKandidatu", spolIdParameter, korisnikIdParameter, datumRodjenjaParameter);
        }
    
        public virtual ObjectResult<asp_Korisnici_SearchByName_Result> asp_Korisnici_SearchByName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Korisnici_SearchByName_Result>("asp_Korisnici_SearchByName", nameParameter);
        }
    
        public virtual ObjectResult<asp_Korisnici_SelectAll_Result> asp_Korisnici_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Korisnici_SelectAll_Result>("asp_Korisnici_SelectAll");
        }
    
        public virtual ObjectResult<asp_Korisnici_SpojenoImePrezime_Result> asp_Korisnici_SpojenoImePrezime()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Korisnici_SpojenoImePrezime_Result>("asp_Korisnici_SpojenoImePrezime");
        }
    
        public virtual ObjectResult<Nullable<int>> asp_Ocjene_DaLiPostojiOcjena(Nullable<int> kandidatId, Nullable<int> korisnikId)
        {
            var kandidatIdParameter = kandidatId.HasValue ?
                new ObjectParameter("KandidatId", kandidatId) :
                new ObjectParameter("KandidatId", typeof(int));
    
            var korisnikIdParameter = korisnikId.HasValue ?
                new ObjectParameter("KorisnikId", korisnikId) :
                new ObjectParameter("KorisnikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("asp_Ocjene_DaLiPostojiOcjena", kandidatIdParameter, korisnikIdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> asp_Ocjene_GetRejtingByKorisnikId(Nullable<int> korisnikId)
        {
            var korisnikIdParameter = korisnikId.HasValue ?
                new ObjectParameter("KorisnikId", korisnikId) :
                new ObjectParameter("KorisnikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("asp_Ocjene_GetRejtingByKorisnikId", korisnikIdParameter);
        }
    
        public virtual ObjectResult<asp_Odgovor_DaLiPostojiOdgovor_Result> asp_Odgovor_DaLiPostojiOdgovor(Nullable<int> pitanjeId)
        {
            var pitanjeIdParameter = pitanjeId.HasValue ?
                new ObjectParameter("PitanjeId", pitanjeId) :
                new ObjectParameter("PitanjeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Odgovor_DaLiPostojiOdgovor_Result>("asp_Odgovor_DaLiPostojiOdgovor", pitanjeIdParameter);
        }
    
        public virtual ObjectResult<asp_Odgovor_GetById_Result> asp_Odgovor_GetById(Nullable<int> odgovorId)
        {
            var odgovorIdParameter = odgovorId.HasValue ?
                new ObjectParameter("OdgovorId", odgovorId) :
                new ObjectParameter("OdgovorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Odgovor_GetById_Result>("asp_Odgovor_GetById", odgovorIdParameter);
        }
    
        public virtual ObjectResult<asp_Odgovor_GetOdgovoriByPitanjeId_Result> asp_Odgovor_GetOdgovoriByPitanjeId(Nullable<int> pitanjeId)
        {
            var pitanjeIdParameter = pitanjeId.HasValue ?
                new ObjectParameter("PitanjeId", pitanjeId) :
                new ObjectParameter("PitanjeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Odgovor_GetOdgovoriByPitanjeId_Result>("asp_Odgovor_GetOdgovoriByPitanjeId", pitanjeIdParameter);
        }
    
        public virtual ObjectResult<asp_Odgovor_SelectAll_Result> asp_Odgovor_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Odgovor_SelectAll_Result>("asp_Odgovor_SelectAll");
        }
    
        public virtual ObjectResult<asp_OznaceniOdgovori_GetById_Result> asp_OznaceniOdgovori_GetById(Nullable<int> oznacenOdgovorId)
        {
            var oznacenOdgovorIdParameter = oznacenOdgovorId.HasValue ?
                new ObjectParameter("OznacenOdgovorId", oznacenOdgovorId) :
                new ObjectParameter("OznacenOdgovorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_OznaceniOdgovori_GetById_Result>("asp_OznaceniOdgovori_GetById", oznacenOdgovorIdParameter);
        }
    
        public virtual ObjectResult<asp_OznaceniOdgovori_GetOznaceniOdgovoriByPitanjeId_Result> asp_OznaceniOdgovori_GetOznaceniOdgovoriByPitanjeId(Nullable<int> polazeId, Nullable<int> pitanjeId)
        {
            var polazeIdParameter = polazeId.HasValue ?
                new ObjectParameter("PolazeId", polazeId) :
                new ObjectParameter("PolazeId", typeof(int));
    
            var pitanjeIdParameter = pitanjeId.HasValue ?
                new ObjectParameter("PitanjeId", pitanjeId) :
                new ObjectParameter("PitanjeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_OznaceniOdgovori_GetOznaceniOdgovoriByPitanjeId_Result>("asp_OznaceniOdgovori_GetOznaceniOdgovoriByPitanjeId", polazeIdParameter, pitanjeIdParameter);
        }
    
        public virtual ObjectResult<asp_OznaceniOdgovori_SelectAll_Result> asp_OznaceniOdgovori_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_OznaceniOdgovori_SelectAll_Result>("asp_OznaceniOdgovori_SelectAll");
        }
    
        public virtual ObjectResult<Nullable<int>> asp_Pitanje_GetBrojPitanjaPoTestu(Nullable<int> testId)
        {
            var testIdParameter = testId.HasValue ?
                new ObjectParameter("TestId", testId) :
                new ObjectParameter("TestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("asp_Pitanje_GetBrojPitanjaPoTestu", testIdParameter);
        }
    
        public virtual ObjectResult<asp_Pitanje_GetById_Result> asp_Pitanje_GetById(Nullable<int> pitanjeId)
        {
            var pitanjeIdParameter = pitanjeId.HasValue ?
                new ObjectParameter("PitanjeId", pitanjeId) :
                new ObjectParameter("PitanjeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Pitanje_GetById_Result>("asp_Pitanje_GetById", pitanjeIdParameter);
        }
    
        public virtual ObjectResult<asp_Pitanje_GetPitanjaByTestID_Result> asp_Pitanje_GetPitanjaByTestID(Nullable<int> testId)
        {
            var testIdParameter = testId.HasValue ?
                new ObjectParameter("TestId", testId) :
                new ObjectParameter("TestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Pitanje_GetPitanjaByTestID_Result>("asp_Pitanje_GetPitanjaByTestID", testIdParameter);
        }
    
        public virtual ObjectResult<Pitanjel_Result> asp_Pitanje_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pitanjel_Result>("asp_Pitanje_SelectAll");
        }
    
        public virtual ObjectResult<asp_Podkategorija_GetById_Result> asp_Podkategorija_GetById(Nullable<int> podkategorijaId)
        {
            var podkategorijaIdParameter = podkategorijaId.HasValue ?
                new ObjectParameter("PodkategorijaId", podkategorijaId) :
                new ObjectParameter("PodkategorijaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Podkategorija_GetById_Result>("asp_Podkategorija_GetById", podkategorijaIdParameter);
        }
    
        public virtual ObjectResult<asp_Podkategorija_SelectAll_Result> asp_Podkategorija_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Podkategorija_SelectAll_Result>("asp_Podkategorija_SelectAll");
        }
    
        public virtual ObjectResult<asp_Podkategorije_GetByKategorijaId_Result> asp_Podkategorije_GetByKategorijaId(Nullable<int> kategorijaId)
        {
            var kategorijaIdParameter = kategorijaId.HasValue ?
                new ObjectParameter("KategorijaId", kategorijaId) :
                new ObjectParameter("KategorijaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Podkategorije_GetByKategorijaId_Result>("asp_Podkategorije_GetByKategorijaId", kategorijaIdParameter);
        }
    
        public virtual ObjectResult<asp_Polaze_GetById_Result> asp_Polaze_GetById(Nullable<int> polazeId)
        {
            var polazeIdParameter = polazeId.HasValue ?
                new ObjectParameter("PolazeId", polazeId) :
                new ObjectParameter("PolazeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Polaze_GetById_Result>("asp_Polaze_GetById", polazeIdParameter);
        }
    
        public virtual ObjectResult<asp_Polaze_GetPolazeByKandidatId_Result> asp_Polaze_GetPolazeByKandidatId(Nullable<int> kandidatId)
        {
            var kandidatIdParameter = kandidatId.HasValue ?
                new ObjectParameter("KandidatId", kandidatId) :
                new ObjectParameter("KandidatId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Polaze_GetPolazeByKandidatId_Result>("asp_Polaze_GetPolazeByKandidatId", kandidatIdParameter);
        }
    
        public virtual ObjectResult<asp_Polaze_SelectAll_Result> asp_Polaze_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Polaze_SelectAll_Result>("asp_Polaze_SelectAll");
        }
    
        public virtual ObjectResult<asp_provjera_nacina_placanja_Result> asp_provjera_nacina_placanja(Nullable<int> kandidatId)
        {
            var kandidatIdParameter = kandidatId.HasValue ?
                new ObjectParameter("kandidatId", kandidatId) :
                new ObjectParameter("kandidatId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_provjera_nacina_placanja_Result>("asp_provjera_nacina_placanja", kandidatIdParameter);
        }
    
        public virtual ObjectResult<asp_Provjera_Uplate_Result> asp_Provjera_Uplate(Nullable<int> kandidatId, Nullable<int> uplataId)
        {
            var kandidatIdParameter = kandidatId.HasValue ?
                new ObjectParameter("kandidatId", kandidatId) :
                new ObjectParameter("kandidatId", typeof(int));
    
            var uplataIdParameter = uplataId.HasValue ?
                new ObjectParameter("uplataId", uplataId) :
                new ObjectParameter("uplataId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Provjera_Uplate_Result>("asp_Provjera_Uplate", kandidatIdParameter, uplataIdParameter);
        }
    
        public virtual ObjectResult<asp_report_Result> asp_report(Nullable<System.DateTime> od, Nullable<System.DateTime> @do, Nullable<int> testId, Nullable<int> kandidatId)
        {
            var odParameter = od.HasValue ?
                new ObjectParameter("Od", od) :
                new ObjectParameter("Od", typeof(System.DateTime));
    
            var doParameter = @do.HasValue ?
                new ObjectParameter("Do", @do) :
                new ObjectParameter("Do", typeof(System.DateTime));
    
            var testIdParameter = testId.HasValue ?
                new ObjectParameter("TestId", testId) :
                new ObjectParameter("TestId", typeof(int));
    
            var kandidatIdParameter = kandidatId.HasValue ?
                new ObjectParameter("KandidatId", kandidatId) :
                new ObjectParameter("KandidatId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_report_Result>("asp_report", odParameter, doParameter, testIdParameter, kandidatIdParameter);
        }
    
        public virtual ObjectResult<asp_Rezultat_GetRezultatiTestovaReport_Result> asp_Rezultat_GetRezultatiTestovaReport(Nullable<int> brojDana, Nullable<int> testId)
        {
            var brojDanaParameter = brojDana.HasValue ?
                new ObjectParameter("BrojDana", brojDana) :
                new ObjectParameter("BrojDana", typeof(int));
    
            var testIdParameter = testId.HasValue ?
                new ObjectParameter("TestId", testId) :
                new ObjectParameter("TestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Rezultat_GetRezultatiTestovaReport_Result>("asp_Rezultat_GetRezultatiTestovaReport", brojDanaParameter, testIdParameter);
        }
    
        public virtual ObjectResult<asp_Spol_SelectAll_Result> asp_Spol_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Spol_SelectAll_Result>("asp_Spol_SelectAll");
        }
    
        public virtual ObjectResult<asp_Termin_DaLiJeSlobodanTermin_Result> asp_Termin_DaLiJeSlobodanTermin(Nullable<System.DateTime> terminDate, Nullable<System.TimeSpan> terminTime, Nullable<int> voziloId, Nullable<int> korisnikId, Nullable<int> kandidatId)
        {
            var terminDateParameter = terminDate.HasValue ?
                new ObjectParameter("TerminDate", terminDate) :
                new ObjectParameter("TerminDate", typeof(System.DateTime));
    
            var terminTimeParameter = terminTime.HasValue ?
                new ObjectParameter("TerminTime", terminTime) :
                new ObjectParameter("TerminTime", typeof(System.TimeSpan));
    
            var voziloIdParameter = voziloId.HasValue ?
                new ObjectParameter("VoziloId", voziloId) :
                new ObjectParameter("VoziloId", typeof(int));
    
            var korisnikIdParameter = korisnikId.HasValue ?
                new ObjectParameter("KorisnikId", korisnikId) :
                new ObjectParameter("KorisnikId", typeof(int));
    
            var kandidatIdParameter = kandidatId.HasValue ?
                new ObjectParameter("KandidatId", kandidatId) :
                new ObjectParameter("KandidatId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Termin_DaLiJeSlobodanTermin_Result>("asp_Termin_DaLiJeSlobodanTermin", terminDateParameter, terminTimeParameter, voziloIdParameter, korisnikIdParameter, kandidatIdParameter);
        }
    
        public virtual ObjectResult<asp_Termin_GetById_Result> asp_Termin_GetById(Nullable<int> terminId)
        {
            var terminIdParameter = terminId.HasValue ?
                new ObjectParameter("TerminId", terminId) :
                new ObjectParameter("TerminId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Termin_GetById_Result>("asp_Termin_GetById", terminIdParameter);
        }
    
        public virtual ObjectResult<asp_Termin_GetByKandidatId_Result> asp_Termin_GetByKandidatId(Nullable<int> kandidatId)
        {
            var kandidatIdParameter = kandidatId.HasValue ?
                new ObjectParameter("KandidatId", kandidatId) :
                new ObjectParameter("KandidatId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Termin_GetByKandidatId_Result>("asp_Termin_GetByKandidatId", kandidatIdParameter);
        }
    
        public virtual ObjectResult<asp_Termin_SearchByName_Result> asp_Termin_SearchByName(string imePrezime)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Termin_SearchByName_Result>("asp_Termin_SearchByName", imePrezimeParameter);
        }
    
        public virtual ObjectResult<asp_Termin_SelectAll_Result> asp_Termin_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Termin_SelectAll_Result>("asp_Termin_SelectAll");
        }
    
        public virtual ObjectResult<asp_Test_DaLiPostojiTestSaPodkategorijom_Result> asp_Test_DaLiPostojiTestSaPodkategorijom(string naziv, Nullable<int> podkategorijaId)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var podkategorijaIdParameter = podkategorijaId.HasValue ?
                new ObjectParameter("PodkategorijaId", podkategorijaId) :
                new ObjectParameter("PodkategorijaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Test_DaLiPostojiTestSaPodkategorijom_Result>("asp_Test_DaLiPostojiTestSaPodkategorijom", nazivParameter, podkategorijaIdParameter);
        }
    
        public virtual ObjectResult<asp_Test_GetById_Result> asp_Test_GetById(Nullable<int> testId)
        {
            var testIdParameter = testId.HasValue ?
                new ObjectParameter("TestId", testId) :
                new ObjectParameter("TestId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Test_GetById_Result>("asp_Test_GetById", testIdParameter);
        }
    
        public virtual ObjectResult<asp_Test_GetByIzborNaziv_Result> asp_Test_GetByIzborNaziv(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Test_GetByIzborNaziv_Result>("asp_Test_GetByIzborNaziv", nazivParameter);
        }
    
        public virtual ObjectResult<asp_Test_Select_All_Result> asp_Test_GetTestByName(string nazivTesta)
        {
            var nazivTestaParameter = nazivTesta != null ?
                new ObjectParameter("nazivTesta", nazivTesta) :
                new ObjectParameter("nazivTesta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Test_Select_All_Result>("asp_Test_GetTestByName", nazivTestaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> asp_Test_GetTestId(string naziv, Nullable<int> podkategorijaId)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var podkategorijaIdParameter = podkategorijaId.HasValue ?
                new ObjectParameter("PodkategorijaId", podkategorijaId) :
                new ObjectParameter("PodkategorijaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("asp_Test_GetTestId", nazivParameter, podkategorijaIdParameter);
        }
    
        public virtual ObjectResult<asp_Test_NazivPodkategorija_Result> asp_Test_NazivPodkategorija()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Test_NazivPodkategorija_Result>("asp_Test_NazivPodkategorija");
        }
    
        public virtual ObjectResult<asp_Test_Select_All_Result> asp_Test_Select_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Test_Select_All_Result>("asp_Test_Select_All");
        }
    
        public virtual ObjectResult<asp_Testovi_GetRecommendedByKandidatId_Result> asp_Testovi_GetRecommendedByKandidatId(Nullable<int> kandidatId)
        {
            var kandidatIdParameter = kandidatId.HasValue ?
                new ObjectParameter("KandidatId", kandidatId) :
                new ObjectParameter("KandidatId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Testovi_GetRecommendedByKandidatId_Result>("asp_Testovi_GetRecommendedByKandidatId", kandidatIdParameter);
        }
    
        public virtual ObjectResult<asp_Testovi_GetTestoviByPodkategorijaID_Result> asp_Testovi_GetTestoviByPodkategorijaID(Nullable<int> podkategorijaId)
        {
            var podkategorijaIdParameter = podkategorijaId.HasValue ?
                new ObjectParameter("PodkategorijaId", podkategorijaId) :
                new ObjectParameter("PodkategorijaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Testovi_GetTestoviByPodkategorijaID_Result>("asp_Testovi_GetTestoviByPodkategorijaID", podkategorijaIdParameter);
        }
    
        public virtual ObjectResult<asp_TipPitanja_GetById_Result> asp_TipPitanja_GetById(Nullable<int> tipPitanjaId)
        {
            var tipPitanjaIdParameter = tipPitanjaId.HasValue ?
                new ObjectParameter("TipPitanjaId", tipPitanjaId) :
                new ObjectParameter("TipPitanjaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_TipPitanja_GetById_Result>("asp_TipPitanja_GetById", tipPitanjaIdParameter);
        }
    
        public virtual ObjectResult<asp_TipPitanja_SelectAll_Result> asp_TipPitanja_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_TipPitanja_SelectAll_Result>("asp_TipPitanja_SelectAll");
        }
    
        public virtual ObjectResult<asp_Uloge_GetUlogeByKorisnikId_Result> asp_Uloge_GetUlogeByKorisnikId(Nullable<int> korisnikId)
        {
            var korisnikIdParameter = korisnikId.HasValue ?
                new ObjectParameter("KorisnikId", korisnikId) :
                new ObjectParameter("KorisnikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Uloge_GetUlogeByKorisnikId_Result>("asp_Uloge_GetUlogeByKorisnikId", korisnikIdParameter);
        }
    
        public virtual ObjectResult<asp_Uloge_SelectAll_Result> asp_Uloge_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Uloge_SelectAll_Result>("asp_Uloge_SelectAll");
        }
    
        public virtual ObjectResult<asp_Upisuje_GetById_Result> asp_Upisuje_GetById(Nullable<int> upisujeId)
        {
            var upisujeIdParameter = upisujeId.HasValue ?
                new ObjectParameter("UpisujeId", upisujeId) :
                new ObjectParameter("UpisujeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Upisuje_GetById_Result>("asp_Upisuje_GetById", upisujeIdParameter);
        }
    
        public virtual ObjectResult<asp_Upisuje_SearchByName_Result> asp_Upisuje_SearchByName(string imePrezime)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Upisuje_SearchByName_Result>("asp_Upisuje_SearchByName", imePrezimeParameter);
        }
    
        public virtual ObjectResult<asp_upisuje_SellectAll_Result> asp_upisuje_SellectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_upisuje_SellectAll_Result>("asp_upisuje_SellectAll");
        }
    
        public virtual ObjectResult<asp_Uplata_GetById_Result> asp_Uplata_GetById(Nullable<int> uplataId)
        {
            var uplataIdParameter = uplataId.HasValue ?
                new ObjectParameter("UplataId", uplataId) :
                new ObjectParameter("UplataId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Uplata_GetById_Result>("asp_Uplata_GetById", uplataIdParameter);
        }
    
        public virtual ObjectResult<asp_Uplate_SelectAll_Result> asp_Uplate_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Uplate_SelectAll_Result>("asp_Uplate_SelectAll");
        }
    
        public virtual ObjectResult<asp_Vozilo_GetById_Result> asp_Vozilo_GetById(Nullable<int> voziloId)
        {
            var voziloIdParameter = voziloId.HasValue ?
                new ObjectParameter("VoziloId", voziloId) :
                new ObjectParameter("VoziloId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Vozilo_GetById_Result>("asp_Vozilo_GetById", voziloIdParameter);
        }
    
        public virtual ObjectResult<asp_Vozilo_SelectAll_Result> asp_Vozilo_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Vozilo_SelectAll_Result>("asp_Vozilo_SelectAll");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<asp_Korisnici_SelectByUsername_Result> asp_Korisnici_SelectByUsername(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Korisnici_SelectByUsername_Result>("asp_Korisnici_SelectByUsername", userNameParameter);
        }
    
        public virtual ObjectResult<asp_Podaci_Za_KNN_Result> asp_Podaci_Za_KNN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Podaci_Za_KNN_Result>("asp_Podaci_Za_KNN");
        }
    
        public virtual ObjectResult<asp_Podaci_Za_KNN_Result> asp_NepolozeniKandidati(Nullable<int> kandidatId)
        {
            var kandidatIdParameter = kandidatId.HasValue ?
                new ObjectParameter("KandidatId", kandidatId) :
                new ObjectParameter("KandidatId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Podaci_Za_KNN_Result>("asp_NepolozeniKandidati", kandidatIdParameter);
        }
    
        public virtual ObjectResult<asp_Tip_Ispita_SelectAll_Result> asp_Tip_Ispita_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_Tip_Ispita_SelectAll_Result>("asp_Tip_Ispita_SelectAll");
        }
    
        public virtual ObjectResult<asp_VozackiIspit_Result> asp_VozackiIspit(string imePrezime)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("imePrezime", imePrezime) :
                new ObjectParameter("imePrezime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_VozackiIspit_Result>("asp_VozackiIspit", imePrezimeParameter);
        }
    
        public virtual ObjectResult<asp_VozackiIspit_SelectAll_Result> asp_VozackiIspit_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<asp_VozackiIspit_SelectAll_Result>("asp_VozackiIspit_SelectAll");
        }
    }
}
