//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto_skolaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OznaceniOdgovori
    {
        public int OznacenOdgovorId { get; set; }
        public int PolazeId { get; set; }
        public int PitanjeId { get; set; }
        public int OdgovorId { get; set; }
    
        public virtual Odgovor Odgovor { get; set; }
        public virtual Pitanje Pitanje { get; set; }
        public virtual Polaze Polaze { get; set; }
    }
}
