//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto_skolaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polaze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polaze()
        {
            this.OznaceniOdgovori = new HashSet<OznaceniOdgovori>();
        }
    
        public int PolazeId { get; set; }
        public System.DateTime VrijemePocetka { get; set; }
        public Nullable<System.DateTime> VrijemeZavrsetka { get; set; }
        public Nullable<int> RezultatId { get; set; }
        public int TestId { get; set; }
        public int KandidatId { get; set; }
    
        public virtual Kandidati Kandidati { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OznaceniOdgovori> OznaceniOdgovori { get; set; }
        public virtual Rezultat Rezultat { get; set; }
        public virtual Test Test { get; set; }
    }
}
