//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto_skolaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StrucnaSprema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StrucnaSprema()
        {
            this.Kandidati = new HashSet<Kandidati>();
        }
    
        public int StrucnaSpremaId { get; set; }
        public string Naziv { get; set; }
        public Nullable<int> StepenObrazovanja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kandidati> Kandidati { get; set; }
    }
}
