//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto_skolaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VozackiIspit
    {
        public int VozackiIspitId { get; set; }
        public int KandidatId { get; set; }
        public System.DateTime Datum { get; set; }
        public int TipIspitaId { get; set; }
        public bool IsPolozio { get; set; }
    
        public virtual Kandidati Kandidati { get; set; }
        public virtual TipIspita TipIspita { get; set; }
    }
}
