//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto_skolaUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("auto_skolaUI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o kandidatu..
        /// </summary>
        internal static string add_kandidat_succ {
            get {
                return ResourceManager.GetString("add_kandidat_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odgovori su uspjesno spremljeni..
        /// </summary>
        internal static string add_odgovor_succ {
            get {
                return ResourceManager.GetString("add_odgovor_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali pitanje..
        /// </summary>
        internal static string add_pitanje_succ {
            get {
                return ResourceManager.GetString("add_pitanje_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali termin..
        /// </summary>
        internal static string add_termin_succ {
            get {
                return ResourceManager.GetString("add_termin_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali test..
        /// </summary>
        internal static string add_test_succ {
            get {
                return ResourceManager.GetString("add_test_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upješno pohranjeni podaci..
        /// </summary>
        internal static string add_upis_succ {
            get {
                return ResourceManager.GetString("add_upis_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o korisniku.
        /// </summary>
        internal static string add_user_succ {
            get {
                return ResourceManager.GetString("add_user_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa je obavezna..
        /// </summary>
        internal static string adrr_req {
            get {
                return ResourceManager.GetString("adrr_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir automobila je obavezan..
        /// </summary>
        internal static string automobil_req {
            get {
                return ResourceManager.GetString("automobil_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobil je zauzet u odabranom terminu..
        /// </summary>
        internal static string automobil_termin_err {
            get {
                return ResourceManager.GetString("automobil_termin_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik uspješno obrisan.
        /// </summary>
        internal static string dell_user_succ {
            get {
                return ResourceManager.GetString("dell_user_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmjenili pitanje..
        /// </summary>
        internal static string edit_pitanje_succ {
            get {
                return ResourceManager.GetString("edit_pitanje_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmjenili termin..
        /// </summary>
        internal static string edit_termin_succ {
            get {
                return ResourceManager.GetString("edit_termin_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmjenili podatke o korisniku.
        /// </summary>
        internal static string edit_user_succ {
            get {
                return ResourceManager.GetString("edit_user_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa je zauzeta..
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je u pogrešnom formatu..
        /// </summary>
        internal static string email_err {
            get {
                return ResourceManager.GetString("email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je obavezan..
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno..
        /// </summary>
        internal static string fname_req {
            get {
                return ResourceManager.GetString("fname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruktor je zauzet u odabranom terminu..
        /// </summary>
        internal static string instruktor_termin_err {
            get {
                return ResourceManager.GetString("instruktor_termin_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir kandidata je obavezan..
        /// </summary>
        internal static string kandidat_req {
            get {
                return ResourceManager.GetString("kandidat_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste označili kandidata kojeg želite izmjeniti..
        /// </summary>
        internal static string kandidat_select_req {
            get {
                return ResourceManager.GetString("kandidat_select_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kandidat je zauzet u odabranom terminu..
        /// </summary>
        internal static string kandidat_termin_err {
            get {
                return ResourceManager.GetString("kandidat_termin_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno..
        /// </summary>
        internal static string lname_req {
            get {
                return ResourceManager.GetString("lname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste neispravnu lozinku.
        /// </summary>
        internal static string login_pass_err {
            get {
                return ResourceManager.GetString("login_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos lozinke je obavezan..
        /// </summary>
        internal static string login_pass_req {
            get {
                return ResourceManager.GetString("login_pass_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime nije pronađeno ili je vaš nalog neaktivan.
        /// </summary>
        internal static string login_user_err {
            get {
                return ResourceManager.GetString("login_user_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos korisničkog imena je obavezan..
        /// </summary>
        internal static string login_username_req {
            get {
                return ResourceManager.GetString("login_username_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje obavezno, pitanje mora imati bar 2 odgovora.
        /// </summary>
        internal static string odgovor1_req {
            get {
                return ResourceManager.GetString("odgovor1_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitanje mora imati bar 2 odgovora.
        /// </summary>
        internal static string odgovor2_req {
            get {
                return ResourceManager.GetString("odgovor2_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password mora sadržavati najmanje 6 karaktera.
        /// </summary>
        internal static string pass_err {
            get {
                return ResourceManager.GetString("pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password je obavezan..
        /// </summary>
        internal static string pass_req {
            get {
                return ResourceManager.GetString("pass_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isto pitanje je već pohranjeno u bazu..
        /// </summary>
        internal static string pitanje_con {
            get {
                return ResourceManager.GetString("pitanje_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitanje je obavezno..
        /// </summary>
        internal static string pitanje_req {
            get {
                return ResourceManager.GetString("pitanje_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste označili pitanje koje želite izmjeniti..
        /// </summary>
        internal static string pitanje_select_req {
            get {
                return ResourceManager.GetString("pitanje_select_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir podkategorije je obavezan..
        /// </summary>
        internal static string podkategorija_req {
            get {
                return ResourceManager.GetString("podkategorija_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spol je obavezno polje..
        /// </summary>
        internal static string spol_req {
            get {
                return ResourceManager.GetString("spol_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona je obavezan..
        /// </summary>
        internal static string tel_req {
            get {
                return ResourceManager.GetString("tel_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste označili termin koji želite izmjeniti..
        /// </summary>
        internal static string termin_select_req {
            get {
                return ResourceManager.GetString("termin_select_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test je obavezan..
        /// </summary>
        internal static string test_req {
            get {
                return ResourceManager.GetString("test_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv testa je obavezan..
        /// </summary>
        internal static string testNaziv_req {
            get {
                return ResourceManager.GetString("testNaziv_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test sa istim nazivom je dodat za odabranu kategoriju..
        /// </summary>
        internal static string testNaziv_uniq {
            get {
                return ResourceManager.GetString("testNaziv_uniq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip pitanja je obavezan..
        /// </summary>
        internal static string tipPitanja_req {
            get {
                return ResourceManager.GetString("tipPitanja_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir uloge je obavezan..
        /// </summary>
        internal static string uloge_req {
            get {
                return ResourceManager.GetString("uloge_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime mora sadržavati najmanje 3 karaktera.
        /// </summary>
        internal static string uname_lng {
            get {
                return ResourceManager.GetString("uname_lng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno..
        /// </summary>
        internal static string uname_req {
            get {
                return ResourceManager.GetString("uname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vec je uplacena .
        /// </summary>
        internal static string uplata_uniq {
            get {
                return ResourceManager.GetString("uplata_uniq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir instruktora je obavezan..
        /// </summary>
        internal static string user_req {
            get {
                return ResourceManager.GetString("user_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste označili korisnika kojeg želite izmjeniti..
        /// </summary>
        internal static string user_select_req {
            get {
                return ResourceManager.GetString("user_select_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto..
        /// </summary>
        internal static string username_con {
            get {
                return ResourceManager.GetString("username_con", resourceCulture);
            }
        }
    }
}
